set -g mouse on
set -g history-limit 100000
set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-style "bg=colour234 fg=colour137"
set -g status-left "#[fg=colour226,bold] olymp-station #[default]"
set -g status-right "#[fg=colour39] %Y-%m-%d %H:%M "
set -g status-left-length 30
setw -g window-status-current-style "bg=colour39 fg=colour234 bold"
