eve-ng-host: http://36.50.7.52:40117/
user: admin
pass: i@m}Q}!*%NV
telnet port ажиллахгүй байгаа бөгөөд html5 colsole оор хандаж байгаа.
заавар байгаа газар: http://36.50.7.44:3000/tasks
vrrp ийн тохиргоо дээр vlan 30 гэж буруу бичсэн vlan 20 шүү гэж зохион байгуулагчид хэлж байна.